create table if not exists public.shopping_items (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  owner_profile_id uuid not null references public.profiles(id) on delete cascade,
  schedule_item_id bigint references public.schedule_items(id) on delete set null,
  client_id text not null,
  name text not null,
  quantity integer not null default 1,
  note text not null default '',
  is_purchased boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shopping_items_client_id_key
    unique (trip_id, owner_profile_id, client_id),
  constraint shopping_items_name_check
    check (char_length(trim(name)) between 1 and 160),
  constraint shopping_items_quantity_check
    check (quantity between 1 and 999),
  constraint shopping_items_note_check
    check (char_length(note) <= 1000)
);

create index if not exists shopping_items_owner_trip_idx
  on public.shopping_items(owner_profile_id, trip_id, is_purchased, created_at);

create index if not exists shopping_items_schedule_item_id_idx
  on public.shopping_items(schedule_item_id)
  where schedule_item_id is not null;

create or replace function private.validate_shopping_item_scope()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if new.schedule_item_id is not null
    and private.trip_id_for_schedule_item(new.schedule_item_id) <> new.trip_id
  then
    raise exception 'Shopping item activity must belong to the same trip.'
      using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists shopping_items_validate_scope on public.shopping_items;
create trigger shopping_items_validate_scope
  before insert or update on public.shopping_items
  for each row execute function private.validate_shopping_item_scope();

drop trigger if exists shopping_items_set_updated_at on public.shopping_items;
create trigger shopping_items_set_updated_at
  before update on public.shopping_items
  for each row execute function public.set_updated_at();

alter table public.shopping_items enable row level security;

drop policy if exists shopping_items_select_owner on public.shopping_items;
create policy shopping_items_select_owner on public.shopping_items
  for select to authenticated
  using (
    owner_profile_id = (select auth.uid())
    and private.is_trip_member(trip_id)
  );

drop policy if exists shopping_items_insert_owner on public.shopping_items;
create policy shopping_items_insert_owner on public.shopping_items
  for insert to authenticated
  with check (
    owner_profile_id = (select auth.uid())
    and private.is_trip_member(trip_id)
  );

drop policy if exists shopping_items_update_owner on public.shopping_items;
create policy shopping_items_update_owner on public.shopping_items
  for update to authenticated
  using (
    owner_profile_id = (select auth.uid())
    and private.is_trip_member(trip_id)
  )
  with check (
    owner_profile_id = (select auth.uid())
    and private.is_trip_member(trip_id)
  );

drop policy if exists shopping_items_delete_owner on public.shopping_items;
create policy shopping_items_delete_owner on public.shopping_items
  for delete to authenticated
  using (
    owner_profile_id = (select auth.uid())
    and private.is_trip_member(trip_id)
  );

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shopping_items'
  ) then
    alter publication supabase_realtime add table public.shopping_items;
  end if;
end;
$$;
