-- Shared contract for the Flutter Travel Companion. Existing website payload
-- replacement keeps working because the new trip/activity columns have safe defaults.

begin;

alter table public.trips
  add column if not exists timezone text not null default 'Asia/Tokyo',
  add column if not exists default_leave_buffer_minutes integer not null default 10;

alter table public.trips
  drop constraint if exists trips_default_leave_buffer_minutes_check;

alter table public.trips
  add constraint trips_default_leave_buffer_minutes_check
  check (default_leave_buffer_minutes between 0 and 120);

alter table public.schedule_items
  add column if not exists preferred_travel_mode text not null default 'TRANSIT',
  add column if not exists leave_buffer_minutes integer,
  add column if not exists leave_time_override time,
  add column if not exists reminder_enabled boolean not null default true;

alter table public.schedule_items
  drop constraint if exists schedule_items_preferred_travel_mode_check,
  drop constraint if exists schedule_items_leave_buffer_minutes_check;

alter table public.schedule_items
  add constraint schedule_items_preferred_travel_mode_check
  check (preferred_travel_mode in ('TRANSIT', 'WALK', 'DRIVE')),
  add constraint schedule_items_leave_buffer_minutes_check
  check (leave_buffer_minutes is null or leave_buffer_minutes between 0 and 120);

create or replace function private.trip_id_for_schedule_item(target_schedule_item_id bigint)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select day.trip_id
  from public.schedule_items item
  join public.trip_days day on day.id = item.trip_day_id
  where item.id = target_schedule_item_id;
$$;

create table if not exists public.schedule_item_resources (
  id bigint generated by default as identity primary key,
  schedule_item_id bigint not null references public.schedule_items(id) on delete cascade,
  client_id text not null,
  resource_type text not null,
  label text not null,
  reference text not null default '',
  url text not null default '',
  notes text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_item_resources_type_check check (resource_type in ('booking', 'ticket', 'link')),
  constraint schedule_item_resources_client_id_key unique (schedule_item_id, client_id)
);

create index if not exists schedule_item_resources_schedule_item_id_idx
  on public.schedule_item_resources(schedule_item_id, sort_order);

create trigger schedule_item_resources_set_updated_at
  before update on public.schedule_item_resources
  for each row execute function public.set_updated_at();

create table if not exists public.trip_notes (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  client_id text not null,
  trip_day_id bigint references public.trip_days(id) on delete set null,
  schedule_item_id bigint references public.schedule_items(id) on delete set null,
  author_profile_id uuid not null references public.profiles(id) on delete restrict,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_notes_body_check check (char_length(trim(body)) between 1 and 4000),
  constraint trip_notes_client_id_key unique (trip_id, client_id)
);

create index if not exists trip_notes_trip_id_created_at_idx on public.trip_notes(trip_id, created_at desc);
create index if not exists trip_notes_schedule_item_id_idx on public.trip_notes(schedule_item_id) where schedule_item_id is not null;

create or replace function private.validate_trip_note_scope()
returns trigger
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if new.trip_day_id is not null and not exists (
    select 1 from public.trip_days where id = new.trip_day_id and trip_id = new.trip_id
  ) then
    raise exception 'Trip note day must belong to the same trip.' using errcode = '23514';
  end if;

  if new.schedule_item_id is not null and private.trip_id_for_schedule_item(new.schedule_item_id) <> new.trip_id then
    raise exception 'Trip note activity must belong to the same trip.' using errcode = '23514';
  end if;
  return new;
end;
$$;

create trigger trip_notes_validate_scope
  before insert or update on public.trip_notes
  for each row execute function private.validate_trip_note_scope();

create trigger trip_notes_set_updated_at
  before update on public.trip_notes
  for each row execute function public.set_updated_at();

alter table public.schedule_item_resources enable row level security;
alter table public.trip_notes enable row level security;

create policy schedule_item_resources_select_member on public.schedule_item_resources
  for select to authenticated
  using (private.is_trip_member(private.trip_id_for_schedule_item(schedule_item_id)));

create policy schedule_item_resources_insert_editor on public.schedule_item_resources
  for insert to authenticated
  with check (private.can_edit_trip(private.trip_id_for_schedule_item(schedule_item_id)));

create policy schedule_item_resources_update_editor on public.schedule_item_resources
  for update to authenticated
  using (private.can_edit_trip(private.trip_id_for_schedule_item(schedule_item_id)))
  with check (private.can_edit_trip(private.trip_id_for_schedule_item(schedule_item_id)));

create policy schedule_item_resources_delete_editor on public.schedule_item_resources
  for delete to authenticated
  using (private.can_edit_trip(private.trip_id_for_schedule_item(schedule_item_id)));

create policy trip_notes_select_member on public.trip_notes
  for select to authenticated
  using (private.is_trip_member(trip_id));

create policy trip_notes_insert_editor_as_self on public.trip_notes
  for insert to authenticated
  with check (
    private.can_edit_trip(trip_id)
    and author_profile_id = (select auth.uid())
  );

create policy trip_notes_update_author_or_editor on public.trip_notes
  for update to authenticated
  using (author_profile_id = (select auth.uid()) or private.can_edit_trip(trip_id))
  with check (author_profile_id = (select auth.uid()) or private.can_edit_trip(trip_id));

create policy trip_notes_delete_author_or_editor on public.trip_notes
  for delete to authenticated
  using (author_profile_id = (select auth.uid()) or private.can_edit_trip(trip_id));

create or replace function public.delete_schedule_item(
  target_schedule_item_id bigint,
  expected_updated_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not private.can_edit_trip(private.trip_id_for_schedule_item(target_schedule_item_id)) then
    raise exception 'You do not have permission to delete this activity.' using errcode = '42501';
  end if;

  delete from public.schedule_items
  where id = target_schedule_item_id and updated_at = expected_updated_at;

  if not found then
    raise exception 'This activity changed elsewhere. Reload and try again.' using errcode = '40001';
  end if;
end;
$$;

create or replace function public.delete_idea(
  target_idea_id bigint,
  expected_updated_at timestamptz
)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if not private.can_edit_trip(private.trip_id_for_idea(target_idea_id)) then
    raise exception 'You do not have permission to delete this idea.' using errcode = '42501';
  end if;

  delete from public.ideas
  where id = target_idea_id and updated_at = expected_updated_at;

  if not found then
    raise exception 'This idea changed elsewhere. Reload and try again.' using errcode = '40001';
  end if;
end;
$$;

create or replace function public.promote_idea_to_schedule(
  target_idea_id bigint,
  target_trip_day_id bigint,
  target_start_time time,
  expected_idea_updated_at timestamptz
)
returns bigint
language plpgsql
security definer
set search_path = public, private
as $$
declare
  source_idea public.ideas%rowtype;
  target_trip_id bigint;
  created_schedule_item_id bigint;
begin
  select * into source_idea from public.ideas where id = target_idea_id and updated_at = expected_idea_updated_at;
  if not found then
    raise exception 'This idea changed elsewhere. Reload and try again.' using errcode = '40001';
  end if;

  select trip_id into target_trip_id from public.trip_days where id = target_trip_day_id;
  if target_trip_id is null or target_trip_id <> source_idea.trip_id or not private.can_edit_trip(target_trip_id) then
    raise exception 'You do not have permission to schedule this idea.' using errcode = '42501';
  end if;

  insert into public.schedule_items (
    trip_day_id, client_id, title, category, city, start_time, duration_minutes,
    status, notes, cost, link, map_link, sort_order, place_id, place_name,
    formatted_address, latitude, longitude, google_maps_uri, place_resolved_at
  ) values (
    target_trip_day_id, source_idea.client_id || '-scheduled-' || extract(epoch from clock_timestamp())::bigint,
    source_idea.title, source_idea.category, source_idea.city, target_start_time,
    source_idea.duration_minutes, source_idea.status, source_idea.notes, source_idea.cost,
    source_idea.link, source_idea.map_link, 0, source_idea.place_id, source_idea.place_name,
    source_idea.formatted_address, source_idea.latitude, source_idea.longitude,
    source_idea.google_maps_uri, source_idea.place_resolved_at
  ) returning id into created_schedule_item_id;

  delete from public.ideas where id = target_idea_id;
  return created_schedule_item_id;
end;
$$;

revoke all on function public.delete_schedule_item(bigint, timestamptz) from public, anon;
revoke all on function public.delete_idea(bigint, timestamptz) from public, anon;
revoke all on function public.promote_idea_to_schedule(bigint, bigint, time, timestamptz) from public, anon;
grant execute on function public.delete_schedule_item(bigint, timestamptz) to authenticated;
grant execute on function public.delete_idea(bigint, timestamptz) to authenticated;
grant execute on function public.promote_idea_to_schedule(bigint, bigint, time, timestamptz) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'schedule_item_resources'
  ) then
    alter publication supabase_realtime add table public.schedule_item_resources;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'trip_notes'
  ) then
    alter publication supabase_realtime add table public.trip_notes;
  end if;
end;
$$;

commit;
