create table if not exists public.trip_expenses (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  client_id text not null,
  source_type text not null default 'manual',
  source_client_id text,
  title text not null,
  amount_minor integer not null,
  currency text not null default 'JPY',
  paid_by_traveler_id bigint not null references public.trip_travelers(id) on delete restrict,
  split_type text not null default 'equal',
  expense_date date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_expenses_trip_id_client_id_key unique (trip_id, client_id),
  constraint trip_expenses_source_type_check check (source_type in ('manual', 'schedule_item', 'idea')),
  constraint trip_expenses_amount_minor_check check (amount_minor > 0),
  constraint trip_expenses_currency_check check (currency in ('JPY', 'USD')),
  constraint trip_expenses_split_type_check check (split_type = 'equal')
);

create table if not exists public.trip_expense_participants (
  expense_id bigint not null references public.trip_expenses(id) on delete cascade,
  traveler_id bigint not null references public.trip_travelers(id) on delete restrict,
  share_amount_minor integer not null,
  created_at timestamptz not null default now(),
  constraint trip_expense_participants_pkey primary key (expense_id, traveler_id),
  constraint trip_expense_participants_share_amount_minor_check check (share_amount_minor >= 0)
);

create index if not exists trip_expenses_trip_id_idx on public.trip_expenses(trip_id);
create index if not exists trip_expenses_paid_by_traveler_id_idx on public.trip_expenses(paid_by_traveler_id);
create index if not exists trip_expenses_source_idx on public.trip_expenses(trip_id, source_type, source_client_id);
create index if not exists trip_expense_participants_expense_id_idx on public.trip_expense_participants(expense_id);
create index if not exists trip_expense_participants_traveler_id_idx on public.trip_expense_participants(traveler_id);

create trigger trip_expenses_set_updated_at
  before update on public.trip_expenses
  for each row execute function public.set_updated_at();

create or replace function private.trip_id_for_expense(target_expense_id bigint)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select te.trip_id from public.trip_expenses te where te.id = target_expense_id;
$$;

alter table public.trip_expenses enable row level security;
alter table public.trip_expense_participants enable row level security;

drop policy if exists trip_expenses_select_member on public.trip_expenses;
drop policy if exists trip_expenses_insert_editor on public.trip_expenses;
drop policy if exists trip_expenses_update_editor on public.trip_expenses;
drop policy if exists trip_expenses_delete_editor on public.trip_expenses;
drop policy if exists trip_expense_participants_select_member on public.trip_expense_participants;
drop policy if exists trip_expense_participants_insert_editor on public.trip_expense_participants;
drop policy if exists trip_expense_participants_update_editor on public.trip_expense_participants;
drop policy if exists trip_expense_participants_delete_editor on public.trip_expense_participants;

create policy trip_expenses_select_member on public.trip_expenses
  for select to authenticated
  using (private.is_trip_member(trip_id));

create policy trip_expenses_insert_editor on public.trip_expenses
  for insert to authenticated
  with check (
    private.can_edit_trip(trip_id)
    and trip_id = private.trip_id_for_traveler(paid_by_traveler_id)
  );

create policy trip_expenses_update_editor on public.trip_expenses
  for update to authenticated
  using (private.can_edit_trip(trip_id))
  with check (
    private.can_edit_trip(trip_id)
    and trip_id = private.trip_id_for_traveler(paid_by_traveler_id)
  );

create policy trip_expenses_delete_editor on public.trip_expenses
  for delete to authenticated
  using (private.can_edit_trip(trip_id));

create policy trip_expense_participants_select_member on public.trip_expense_participants
  for select to authenticated
  using (private.is_trip_member(private.trip_id_for_expense(expense_id)));

create policy trip_expense_participants_insert_editor on public.trip_expense_participants
  for insert to authenticated
  with check (
    private.can_edit_trip(private.trip_id_for_expense(expense_id))
    and private.trip_id_for_expense(expense_id) = private.trip_id_for_traveler(traveler_id)
  );

create policy trip_expense_participants_update_editor on public.trip_expense_participants
  for update to authenticated
  using (private.can_edit_trip(private.trip_id_for_expense(expense_id)))
  with check (
    private.can_edit_trip(private.trip_id_for_expense(expense_id))
    and private.trip_id_for_expense(expense_id) = private.trip_id_for_traveler(traveler_id)
  );

create policy trip_expense_participants_delete_editor on public.trip_expense_participants
  for delete to authenticated
  using (private.can_edit_trip(private.trip_id_for_expense(expense_id)));

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'trip_expenses'
  ) then
    alter publication supabase_realtime add table public.trip_expenses;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'trip_expense_participants'
  ) then
    alter publication supabase_realtime add table public.trip_expense_participants;
  end if;
end $$;
